#!/usr/bin/sh
label=${1:$(hostname)}
keyring-minimal get "$label" || (notify-send "Keyring locked or label "${label}" not found!" 'Please unlock the keyring and try again' --icon=dialog-password -u critical && exit 1)
